import React from 'react';

const FAQPage: React.FC = () => {
  return (
    <div className='max-width'> 
      <h2>Frequently Asked Questions (FAQ)</h2>
      <p>
      Welcome to the Frequently Asked Questions (FAQ) page of png2jpg.com! Below, you'll find answers to some of the most common questions about our platform and services. If you have a question that isn't addressed here, please feel free to contact us for further assistance.
      </p>

      <ol>
        <li>
          <strong>What is PNG?</strong>
          <p>
          PNG (Portable Network Graphics) is a versatile image format known for its lossless compression and support for transparency. It is widely used in web graphics, digital art, and other applications where image quality and transparency are crucial.
          </p>
        </li>

        <li>
          <strong>Why convert PNG to JPG and JPG to PNG?</strong>
          <p>
          While PNG offers lossless compression and transparency support, converting PNG images to JPG can significantly reduce file sizes, making them more suitable for web use and storage. Conversely, converting JPG images to PNG preserves image quality and transparency, enhancing their usability in graphic design and editing.
          </p>
        </li>

        <li>
          <strong>How does png2jpeg.com work?</strong>
          <p>
          png2jpeg.com is an online tool that allows users to convert PNG images to JPG and JPG images to PNG formats quickly and easily. Simply upload your PNG or JPG file to the website, select the desired output format, and initiate the conversion process. Once the conversion is complete, you can download the converted file to your device for further use.
          </p>
        </li>

        <li>
          <strong>Is png2jpeg.com free to use?</strong>
          <p>
           Yes, png2jpg.com is completely free to use. There are no subscription fees or hidden charges associated with our platform. Simply visit the website, upload your PNG or JPG file, and convert it to JPG or PNG format at no cost
          </p>
        </li>

        <li>
          <strong>Are there any limitations on file size or number of conversions?</strong>
          <p>
          While png2jpeg.com does not impose strict limitations on file size or the number of conversions, practical constraints may apply based on server capacity and bandwidth. We recommend keeping file sizes reasonable and avoiding excessive use of the platform to ensure optimal performance for all users.
          </p>
        </li>

        <li>
          <strong>Is there a limit to the resolution of images that can be converted?</strong>
          <p>
          png2jpeg.com supports high-resolution images and does not impose strict limitations on image resolution. However, larger image files may take longer to upload and convert, depending on your internet connection speed and server load. We recommend optimizing images for web use to ensure smooth conversion and download processes.
          </p>
        </li>

        <li>
          <strong>Can I convert multiple PNG or JPG images at once?</strong>
          <p>
          Yes, png2jpeg supports the conversion of multiple PNG or JPG images at a time. If you have multiple PNG or JPG images that need to be converted, you can upload and convert them using the website's interface. 
          </p>
        </li>

        <li>
          <strong>Are the converted PNG and JPG files compressed?</strong>
          <p>
          The converted JPG and PNG files generated by png2jpeg are optimized for web use and may undergo compression to reduce file size while maintaining image quality. Our goal is to strike a balance between file size and visual fidelity to ensure fast loading times and optimal performance when sharing or displaying converted images online.
          </p>
        </li>

        <li>
          <strong>How long does it take to convert a PNG or JPG image?</strong>
          <p>
          The conversion time for PNG or JPG images varies depending on factors such as file size, image resolution, and server load. In general, smaller images with lower resolutions will convert more quickly, while larger images may take longer to process. We strive to provide fast and efficient conversion times for all users, but please be patient if processing times are longer than expected.
          </p>
        </li>

        

        <li>
          <strong>Is my data secure when using png2jpeg.com?</strong>
          <p>
          Yes, we take the security and privacy of our users' data seriously at png2jpg.com. We implement robust security measures to protect user information and ensure a safe and secure browsing experience on our platform. Your data will be handled in accordance with our privacy policy, and we will never share your information with third parties without your consent.
          </p>
        </li>

        <li>
          <strong>What should I do if I encounter an issue with png2jpeg.com?</strong>
          <p>
          If you experience any technical issues or have trouble using png2jpg.com, please don't hesitate to contact us for assistance. Our customer support team is here to help troubleshoot problems, answer questions, and ensure that your experience with our platform is as smooth and enjoyable as possible. You can reach us via email, social media, or traditional mail, and we'll do our best to resolve any issues promptly.
          </p>
        </li>
      </ol>

      <p><strong>Contact Us</strong></p>
      <p>
        Still have questions? We're here to help! Contact our team at info@png2jpeg.com for further assistance or clarification. Thank you for choosing avif2png.com—we appreciate your support and look forward to serving you!
      </p>
    </div> 
  );
}

export default FAQPage;
